# Generated by Django 5.1 on 2024-08-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desifoods', '0002_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
