# Generated by Django 5.1 on 2024-08-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desifoods', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
