# Generated by Django 5.1 on 2024-08-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desifoods', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
