# Generated by Django 5.1 on 2024-08-20 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desifoods', '0007_remove_product_quantity_alter_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='name',
        ),
    ]
