# Generated by Django 5.1 on 2024-08-20 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desifoods', '0008_rename_product_order_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', null=True, upload_to='order/photos')),
                ('product', models.CharField(default='', max_length=100, null=True)),
                ('quantity', models.CharField(default='', max_length=200, null=True)),
                ('address', models.TextField(default='', null=True)),
                ('price', models.FloatField(default=0.0, null=True)),
                ('phone', models.CharField(default='', max_length=30, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('date', models.DateField(default=datetime.date.today, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
