# Generated by Django 5.1 on 2024-08-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desifoods', '0009_customerorder_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='customer_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
